### PR TITLE
Script to generate cards using a template

### PR DESCRIPTION
**Pull request by DrDub**
Thanks for making Society available.

I used an online convertor to extract the text from the .pages files and
place it into a text file in the format "title \n <space> content \n\n".

With the SVG files you exported in #5 (thanks!), I created a SVG
template in templates/

The scripts in scripts/ will then produce a separate SVG file for each
of the cards in the text files. If the program "inkscape" is available,
a second script transforms the SVGs into PDFs and PNGs (also included).

The font used originally (Tsukushi) is only available without a license
on Mac OS X. I substituted with a webfont that looked compatible (Nunito)
which is also included.

If you want the files in a different folder, let me know and I can make
changes to the PR (the folders are hard-coded into the scripts).

I can run the script when there are new changes to the cards or I can
write instructions about how to run them under Mac OS X (with some
luck).

### CODE REVIEW

**Comment by andrewtavis** [comment]
Wow this is quite the PR to wake up to on one's birthday! :)

Firstly, happy to make Society available! Thank you so much for all of this effort and the care that you put into all of this! Let me look into the contents a bit just so I understand the process and result before an eventual merge. 

I was actually planning on converting the .pages files to .txt as soon as I realized there was some interest, so thanks for saving me the time. I do have Inskscape (although I'm a pretty novice user), so all of this should work on my end. I can't believe that the cards can be made like this - really a wonderful feature for this repository. 

I'll change the font in the Sketch as well :)

You'd be more than welcome to run the script as cards are written or changed, and maybe I can figure out a mac OS version of it. I'll let you know if I have problems with any of it. Would also be helpful to do a writeup on how all of this is done for the readme, so I'll check back in with you on that :)

Will get back to you on all of this in the next few days, and again thank you so much!

**Comment by andrewtavis** [comment]
A quick question: does it make sense to you that ImgBot makes edits to the submitted files? Will optimize the pngs and svgs in the PR, so just checking. I can also ignore the auto PR from it.

Thanks again!

**Comment by DrDub** [comment]
I think imgbot optimizes for the web. As these files are intended for printing, I'd leave them as-is, at least for the moment.

(Today is your birthday for real? Happy birthday!)

**Review by andrewtavis — APPROVED** [review]

**Comment by andrewtavis** [comment]
Apologies that this took me a bit longer than I originally said it would. Has been a busy week and a bit :)

I removed imgbot from the repository, so the new images will remain as is. I'll export the old component images soon so that they'll be in here in their non-compressed forms as well. I'll also work to create scripts to make the cards on Mac. Your scripts look to be reproducible on my end :) I'll let you know if I change around the directories when I write mine, and will try to just update your scripts if I do so you can just check rather than update. 

Thanks again so much for your work on all of this! Also thanks for the happy birthday 😊

**Pull request merged**
